import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Russo_One } from "next/font/google";
import { Inter } from 'next/font/google';
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // This creates a CSS variable
});
/* Fonts */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const russoOne = Russo_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-russo",
});



/* Metadata */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* Root Layout */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${russoOne.variable}
          ${inter.variable}

          antialiased
        `}>
        <header />
        <main>{children}</main>
      </body>



    </html>
  );
}
